AfricasVoices/CodaV2

webapp/lib/data_model.dart
webapp/lib/main_ui.dart
webapp/lib/playground.dart
webapp/lib/temp_data.dart
webapp/lib/view_model.dart
webapp/web/index.html
webapp/web/main.css
webapp/web/main.dart

Messages can now be imported from a dataset, and I've added some scaffolding functionality for the code selectors.
Demo: https://www.cl.cam.ac.uk/~mcm79/codav2_demos/viewmodel-pr/
I'm planning to add tests for the UI, but wanted to send this first for feedback. I'll add the tests in the next PR.

Adding viewmodel for messages

---

webapp/lib/main_ui.dart

Fix a bug I introduced in c2a5c5b when switched to getAncestors

Fix a bug where the tabbing wouldn't move from the current dropdown, but from the beginning of the table

---

webapp/lib/view_model.dart

This is more of a question rather than a change, but I think when we switched in eaad8ce16f from getting the last label to getting the first, we should have added to the beginning of the label list rather than the end?

Insert label at the beginning of label list when added manually

---

webapp/lib/data_model.dart
webapp/lib/view_model.dart
webapp/web/buttons.css

Demo: https://www.cl.cam.ac.uk/~mcm79/codav2_demos/checkbox-2018-10-15/?dataset=test_dataset_id
What should happen:
- unchecking an unlabelled code should not work
- checking and unchecking a labelled code should work
- unlabelling a code should appear in the console logs and Firebase as SPECIAL-MANUALLY_UNLABELLED
Thanks and please let me know if I've missed anything!

Adjust checkbox and un-coding behaviour

---

webapp/lib/main_ui.dart

Fixes #64 
I introduced this bug when I switched to the real-time way of loading messages.

Select first code selector on initial load of messages

---

data_tools/validate_code_scheme.py
webapp/lib/view_model.dart
webapp/web/main.css

Per @ParthaMoman request (https://github.com/AfricasVoices/CodaV2/issues/112)
I'm not super happy about ln 137 and ln 141 - they add an explicit coupling in the number of elements in the DOM tree between the Code selector and the message tree. Is there a simple way to say 'search upward for first ```message-row```'?

Add active message indicator

---

docs/data_formats.md

@as2388 Gitdiff is being dumb. The changes here are:
```
"StringValue"     : String,       // Required, Unique in code scheme analysis output in string form
"MatchValues"     : List<String>  // Optional, List of strings that tools can use to automatically match this code
```

Data to support pipeline in codes

---

webapp/lib/main_ui.dart
webapp/web/main.css

PTAL @lukechurch 
The key lines are `table-layout: fixed` and `word-wrap: break-word`. The slight changes to the layout for the `seq` column are needed b/c changing the table layout to fixed made the sorting button go to the next line.
Thanks!

Make the table break too long single-word messages on multiple lines

---

data_tools/compute_coding_progress.py
data_tools/firebase_client_wrapper.py

FYI @IsaackMwenda 
This addresses part of the excessive read problem as we aren't repeatedly reading the whole dataset if the metrics weren't present. It's a temporary solution until we have a more complete design in place

Write the metrics back to the dataset if they weren’t there

---

webapp/lib/view_model.dart

This changes the grouping order, so checked messages with any code appear before unchecked ones. This aligns better to what I think the coding workflow with ML support will be.
Deployed to https://coda-dev-229611.firebaseapp.com/?dataset=books2 if you want to observe the result

Group by checked messages

---

functions/package.json

@marianamarasoiu There's a change to the way that Firebase functions are deployed - by the end of March they're going to need pinned versions

Pin Functions version

---

webapp/lib/firebase_tools.dart

@marianamarasoiu I thought I would help - and it turns out I created the bug in the first place.
If autoCode hasn't been clicked, the metrics won't be written into the dataset, so the query object will return null.
Addresses #205 and #204.

Fix NRE if autocoding metrics not present

---

data_tools/get.py

Exporting downloaded messages sorted by the MessageID is confusing, and doesn't match what we upload or what users see in Coda. This makes things more consistent, and allows us to "shard" correctly by pulling an existing dataset then pushing it back again.

Sort downloaded messages by sequence number

---

webapp/pubspec.lock

Upgrading to Dart 2.5.1 also requires:
```
cd webapp
pub upgrade
pub global active webdev
```

Dart 2.5.1 support upgrade packages

---

data_tools/compute_coding_progress.py

Updates the compute_coding_progress command line tool to:
- Support copying segments
- Support usage in the form `$ python compute_coding_progress.py >progress.json` by not printing any logs when using the CLI.

Fix the compute coding progress CLI

---

README.md
webapp/run_dev_local.sh

Following the instructions in the README, I can't actually run Coda correctly locally. This fixes the problem by:
- Making `run_dev_local.sh` executable
- Updating the README to refer to `run_dev_local.sh` instead of `webdev serve`

Fix dev server instructions not working

---

README.md
deployment/deploy.sh

This is what I needed to do to be able to run the deploy scripts. Please correct me if I've misunderstood something.

Make deploy.sh executable and fix errors in deployment documentation

---

webapp/lib/main_ui.dart
webapp/web/index.html

Uses the terminology "message" for consistency with the rest of Coda's user interface and code base.

Add "Next uncoded message" button

---

data_tools/firebase_client_wrapper.py
data_tools/restore.py
webapp/lib/data_model.dart
webapp/lib/firebase_tools.dart
webapp/test/view_model_test.dart

Updates the webapp and data tools to write a 'LastUpdated' field to Coda when updating a message object in Firestore.
Here's an example from the Firebase console when testing against Coda dev (message text omitted):
The changes are backwards-compatible with the current master version of the webapp, but unfortunately not data_tools because they are unable to json-serialize the DateTimeWithNanoseconds objects that Firestore timestamps get deserialized to, so we'd need to upgrade the data_tools versions in the pipelines before updating the webapp.

Set Message.LastUpdated to the Firestore server time when writing to Firestore

---

data_tools/add.py
data_tools/compute_coding_progress.py
data_tools/firebase_client_wrapper.py
data_tools/set.py

This has two main advantages:
- Users of the main function for adding/setting messages no longer need to remember to update the metrics afterwards
- We can update metrics without needing to read the entire dataset from Firestore again, which makes updating the datasets cheaper.
Note that I had to move compute_coding_progress from compute_coding_progress.py to firebase_client_wrapper.py.

Automatically recompute coding progress in firebase_client_wrapper.add_and_update_messages_content_batch

---

data_tools/add.py

It's similar to the print statement we already have for code schemes, it's just pre-upload rather than post-upload.
(I found it helpful to have this extra info when uploading new messages to Coda earlier today.)

Add logging for how many messages to be added vs how many to be skipped

---

data_tools/firebase_client_wrapper.py
data_tools/get.py

Adds support for optionally calling get.py with a previous export of a messages dataset from Coda. When provided with a previous export, get.py will only download messages which have changed in Coda since that export was made, which should reduce the cost of running high frequency pipelines. 
There were a few complexities arising from needing to handle segmented/non-segmented datasets, incremental + non-incremental fetch, and datasets which may or may not have a LastUpdated field set on some or all of the messages. The high level cases and and intended behaviours are:
- Pipelines which upgrade to this commit but don’t enable incremental mode will continue to work just as before, but the exports will now have better consistency guarantees surrounding parallel labelling of segments.
- …

Support incremental get

---

data_tools/add.py
data_tools/firebase_client_wrapper.py

Review #263 first.
This removes unnecessary message reads when adding messages. add.py downloads all the messages to decide which to add, then again in add_and_update_messages_content_batch because that function needs to check for which segment a message is in if it's updating. By providing a function that handles the add case only, we can reduce the second set of reads from the entire dataset to just the latest segment (to check its size), and then to 0 once Coda is updated to work on non-segmented datasets again.

Add firebase_client_wrapper.add_messages_content_batch
