AfricasVoices/CodaV2

webapp/web/index.html

Github was complaining about the format of these link tags

Tweak: Update style for link tags

---

webapp/lib/firebase_constants.dart
webapp/lib/main_ui.dart

This is some sample code for connecting to a Firestore database. I'm looking next at adding an auth flow but I may run out of battery before I can finish that today.

Add test firebase init code

---

webapp/lib/authentication.dart
webapp/lib/main_ui.dart
webapp/web/index.html

This is off master, so I expect a small merging conflict with the other PR, but I don't really mind which you review first.

Hide table and coding buttons when logged out.

---

webapp/lib/main_ui.dart

Demo: https://www.cl.cam.ac.uk/~mcm79/codav2_demos/more-select-dropdown-2018-10-09/
Thanks!

 Select dropdown when clicking around it

---

webapp/lib/authentication.dart
webapp/lib/firebase_tools.dart
webapp/lib/main_ui.dart
webapp/test/view_model_test.dart
webapp/web/index.html
webapp/web/main.css

Demo: 
https://www.cl.cam.ac.uk/~mcm79/codav2_demos/error-and-logged-out-views-2018-10-09/
and
https://www.cl.cam.ac.uk/~mcm79/codav2_demos/error-and-logged-out-views-2018-10-09/?dataset=test-dataset
Thanks!

Separate views for coding, dataset loading error and signed out view

---

webapp/lib/dataset_tools.dart
webapp/lib/firebase_tools.dart

Also changed slightly when we're throwing errors in the temp code to better match a case scenario (only a few URLs are actually valid).
Demo: 
https://www.cl.cam.ac.uk/~mcm79/codav2_demos/10-dataset-2018-10-10/?dataset=dataset-msg-10000

Add test code for generating datasets and adjust that from the URL

---

data_tools/validate_code_scheme.py
docs/data_formats.md
webapp/lib/data_model.dart
webapp/lib/dataset_tools.dart
webapp/lib/firebase_tools.dart
webapp/lib/main_ui.dart
webapp/lib/view_model.dart
webapp/test/data_model_test.dart

- Replace code Maps with a Code object
- Add initial code to pull Schemes from FireBase

WIP: New scheme data structure

---

webapp/lib/firebase_tools.dart
webapp/lib/logger.dart
webapp/lib/main_ui.dart
webapp/lib/view_model.dart

Add initial logging infrastructure

---

.circleci/config.yml
webapp/lib/authentication.dart
webapp/lib/config.dart
webapp/lib/data_model.dart
webapp/lib/firebase_tools.dart
webapp/lib/logger.dart
webapp/lib/mock_auth.dart
webapp/lib/mocks/mock_auth.dart
webapp/lib/sample_data/sample_json_datasets.dart
webapp/test/data_model_test.dart
webapp/test/view_model_test.dart
webapp/test/view_model_test.html

Fixes #39 
Sorry for the large PR. This does a few tangled things which would be a bit tricky to separate:
- configures CircleCI
- fixes tests that were no longer working because of needing a firebase connection
- fixes small issues with some of the sample datasets
- makes data_model_test to use the sample datasets and not define its own
I've configured CircleCI to run for the master branch and branches starting with "circleci-" - does that sound ok?
Thanks!

Configure CircleCI to work with Dart

---

docs/data_formats.md
webapp/lib/authentication.dart
webapp/lib/data_model.dart
webapp/lib/dataset_tools.dart
webapp/lib/firebase_tools.dart
webapp/lib/logger.dart
webapp/lib/sample_data/sample_json_datasets.dart
webapp/lib/view_model.dart
webapp/test/data_model_test.dart
webapp/test/view_model_test.dart

Demo: https://www.cl.cam.ac.uk/~mcm79/codav2_demos/dataset-from-firebase-2018-10-15/?dataset=test_dataset_id
Fixes #33

Load dataset from Firebase

---

.firebaserc_prod
deploy_dev.sh
deploy_prod.sh

Add deploy scripts 
Explicitly specify the deploy target in the scripts rather than trying to modify the rc files

Deploy scripts

---

webapp/lib/view_model.dart
webapp/web/main.css

Addresses #45 
Demo: https://www.cl.cam.ac.uk/~mcm79/codav2_demos/origin-2018-10-17/?dataset=reach_demo

Show the code origin in the UI

---

data_tools/get_dataset_ids.py

Add tool to get and print dataset ids

Get dataset ids

---

webapp/lib/main_ui.dart
webapp/lib/snackbar.dart
webapp/test/view_model_test.html
webapp/web/index.html
webapp/web/main.css

Currently not triggered, but useful to have around.

Add snackbar for displaying notifications, warnings and errors

---

webapp/web/main.css

Addresses #86 
PTAL at the demo and let me know whether it works as expected:
https://www.cl.cam.ac.uk/~mcm79/codav2_demos/codes-bug-2018-10-17/?dataset=reach_demo

Fix the width of the input-group and select element

---

webapp/lib/main_ui.dart
webapp/lib/view_model.dart
webapp/web/main.css

Addresses #85 
Demo: https://www.cl.cam.ac.uk/~mcm79/codav2_demos/display-tweaks-2018-10-18/?dataset=reach_demo
Let me know how it looks and whether you'd like any other adjustments. Thanks!

Display tweaks

---

data_tools/add_users_to_dataset.py

Update add users to match current Firestore data config and allow add/set

---

data_tools/add_users_to_dataset.py

Add check for dataset existence. Fixes #83

---

webapp/web/main.css

Addresses #85 
Demo https://www.cl.cam.ac.uk/~mcm79/codav2_demos/display-tweaks2-2018-10-18/?dataset=reach_demo

Adjust code scheme title to fit on two lines, with scheme id to the right

---

webapp/web/main.css

PTAL, esp at the demo: https://www.cl.cam.ac.uk/~mcm79/codav2_demos/display-tweaks-2018-10-19/?dataset=test_dataset_id
I'm happy to iterate in this PR until we get to a good look of the table header :)

Make the table header sticky and set it visualy apart from other table rows

---

webapp/lib/data_model.dart

Serialise DateTImes as ISO strings

---

webapp/lib/logger.dart
webapp/lib/view_model.dart

TBR @marianamarasoiu 
Fixes #120

Use UTC times

---

example/books-scheme.json

@marianamarasoiu I think it would be a good idea to add a bit more typing to the codes, what do you think of this?

Add control codes to example

---

data_tools/backup.py

Add tool to do a simple export of the whole datastore

Add simple datastore backup tool

---

webapp/lib/main_ui.dart
webapp/test/view_model_test.html
webapp/web/index.html
webapp/web/main.css

Addresses #134 
Demo: https://www.cl.cam.ac.uk/~mcm79/codav2_demos/next-code-2018-10-30/

Add checkbox for whether to jump to next or next uncoded

---

data_tools/schema.py
data_tools/scheme.py
data_tools/validators.py

Data structure wip

---

schema_tools/csv_to_schemata.py
schema_tools/csv_to_scheme.py

Tool to turn a CSV listing a coding scheme into a JSON file, adding special codes

Schema tools

---

webapp/lib/logger.dart
webapp/lib/main_ui.dart

WIP for #106 - @lukechurch let me know what you think of the approach
We may want to replace what we show in the UI with a more user friendly message, though that may mean catching some of the errors we know about earlier and logging them then.

add log.severe and global listener for errors

---

data_tools/compute_coding_progress.py
data_tools/firebase_client_wrapper.py
data_tools/push_coding_progress.py

@marianamarasoiu PTAL
This is currently separated into tools to compute the fraction and a separate tool to push it, as they're in separate firebase databases for security reasons. There is some problem with switching the client authentication after initialisation, so I'm avoiding it using two processes for now. 
The intention is this tool would be executed approximately hourly, and the results pushed to a dashboard

Add tool to periodically report the coding completeness

---

functions/package-lock.json
webapp/lib/main_ui.dart

Offline reviewed by @marianamarasoiu

Harden error handling

---

webapp/lib/main_ui.dart
webapp/web/main.css

Addresses issue #154
Demo: https://www.cl.cam.ac.uk/~mcm79/codav2_demos/sort-button-2018-11-26/
Thanks!

Fix sort button getting hidden by long scheme names

---

webapp/web/main.css

@lukechurch  ptal, thanks!
Also increased the padding slightly to make it look nicer when the table takes up all the width.

Don't restrict the table width

---

.gitignore
deploy_dev.sh
deploy_prod.sh
deploy_wts.sh
webapp/lib/firebase_constants_wts.dart

I think this covers all the changes necessary for adding another deployment.
I can't test it as I don't have access to that project, may I ask you to test it instead?

Deploy scripts for wts experiments

---

deploy_dev.sh
deploy_prod.sh
deploy_wts.sh

Sorry about this, I didn't adjust some of the predeploy verification checks in the previous PR after copy and paste - this should fix them. Thanks!

Fix predeploy verification checks

---

data_tools/add.py
data_tools/firebase_client_wrapper.py
data_tools/restore.py
data_tools/set.py

Review #174 first
Change here is to add restore.py which allows applying a file created by backup.py to an empty datastore. 
We can also use this to create copies of production in test for reproducing issues in a safe environment

Restore tool

---

data_tools/backup.py

@marianamarasoiu It would be useful to be able to archive datasets in the same machine readable format as backup

backup specific project

---

data_tools/compute_coding_progress.py

@IsaackMwenda PTAL
As discussed - this is the first part of making the changes to compute_progress, separating the code for computing the coding results for a dataset for a given id into a function, so that it can be called by add as well

refactor compute_coding_progress

---

data_tools/add.py

@lukechurch PTAL . Have added a line that calls compute_coding_progress function at the end of the file.

Added a line to call compute_coding_progress function at the end of the file

---

data_tools/add.py
data_tools/compute_coding_progress.py

Hi @lukechurch  have renamed the id correctly kindly check.

Renamed id to DATASET_ID

---

webapp/lib/main_ui.dart

Addresses #189 
Demo: https://www.cl.cam.ac.uk/~mcm79/codav2_demos/2018-02-05-checkbox/?dataset=_mariana_test_books
Thanks!

Add Enter as shortcut for accepting a code

---

deployment/coda_dev_constants.json
deployment/interview_constants.json
deployment/prod_constants.json
deployment/wts_constants.json
webapp/lib/firebase_constants.dart

The first of many parts wiring through the pub/sub infrastructure used to drive auto-labelling

Add urls for pub/sub

---

functions/index.js
functions/package-lock.json
functions/package.json

Add support for taking an HTTP request and publishing it into the control plane

Add pub-sub cloud function

---

webapp/lib/firebase_tools.dart

Address review comments

---

schema_tools/csv_to_scheme.py

@as2388 @IsaackMwenda - if you're concerned with the introduction of a Meta CodeType and would like a phased approach we can introduce these as normal codes first, and transition them to meta codes in a subsequent change.
cc @marianamarasoiu

Add new meta codes for question and pushback

---

schema_tools/csv_to_scheme.py

(Fixed some of the minor formatting issues in the file along the way)

Add greeting code

---

docs/data_formats.md

Add descriptions of control and meta codes to data_formats.md

---

data_tools/add.py
data_tools/compute_coding_progress.py
data_tools/duplicate_scheme.py
data_tools/firebase_client_wrapper.py
data_tools/get.py
data_tools/get_dataset_ids.py
data_tools/restore.py
data_tools/set.py

Updates the rest of data_tools to handle segmenting (including setting and getting code schemes, users).
Most of the changes are to firebase_client_wrapper.py, with minimal changes to other users of this library. However, I found lots of duplicated implementations of fcw code in the other data tools scripts, so updated these to use the library functions instead.
cc @IsaackMwenda

Handle segmenting everywhere in data_tools

---

data_tools/backup.py
data_tools/restore.py

This reduces the memory requirements of the backup/restore tools.
Each dataset is exported to a JSON object on one line of the exported JSONL.

Modify backup/restore to export/import jsonl

---

data_tools/Pipfile
data_tools/Pipfile.lock
data_tools/code_merge.py

Can be reviewed independently of #239 but I don't recommend using it without merging #239 first.
Automatically assigns new labels with the id of the merged code when doing a code_merge in a code scheme.

Add code_merge.py

---

README.md

Update readme to reflect the new way of deploying coda web app to firebase

---

webapp/lib/firebase_tools.dart

Fixes #211. Tested by comparing with the outputs of data_tools/compute_coding_progress.py.
There's a question as to how similar the code should read between the two implementations. Trying to match line-for-line would reduce the chance of them differing, but perhaps makes one or both implementations feel unidiomatic for the language. This PR makes the minimum required changes to fix, and leaves the rest of the implementation alone. Happy to align the implementations further in a future PR if requested, possibly by modifying the python rather than the dart.

Update webapp metrics implementation to give same results as data_tools

---

data_tools/add.py
data_tools/firebase_client_wrapper.py

When updating messages, we need to set the message in the segment it is in already, not the latest segment as was done previously, otherwise we'll duplicate the messages in the dataset.
This update also checks/assigns sequence numbers to messages being updated, and pushes some of the sequence number handling logic in add.py into the firebase_client_wrapper.py, which is possible now due to the updated function in firebase_client_wrapper.py.

Set messages correctly in segmented datasets

---

data_tools/add.py

Updates add.py to use f-strings, PEP-8 formatting conventions, and argparse. Closes #266.

Modernise add.py

---

data_tools/add.py

(add_messages_content_batch is the new efficient + cheaper Coda add function that doesn't duplicate expensive read logic already in add.py)

Set sequence numbers in add.py so we can use fcw.add_messages_content_batch
